In [42]:
import pandas as pd

In [43]:
# The url of the wikipedia page
url = 'https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'

In [98]:
df = pd.read_html(url, header = 0)
df

[    Postal Code           Borough  \
 0           M1A      Not assigned
 1           M2A      Not assigned
 2           M3A        North York
 3           M4A        North York
 4           M5A  Downtown Toronto
 ..          ...               ...
 175         M5Z      Not assigned
 176         M6Z      Not assigned
 177         M7Z      Not assigned
 178         M8Z         Etobicoke
 179         M9Z      Not assigned

                                          Neighbourhood
 0                                         Not assigned
 1                                         Not assigned
 2                                            Parkwoods
 3                                     Victoria Village
 4                            Regent Park, Harbourfront
 ..                                                 ...
 175                                       Not assigned
 176                                       Not assigned
 177                                       Not assigned
 178  Mimico NW, The Queensway West, South of Bloor,...
 179                                       Not assigned

 [180 rows x 3 columns],
                                           Unnamed: 0  \
 0  NL NS PE NB QC ON MB SK AB BC NU/NT YT A B C E...
 1                                                 NL
 2                                                  A

                                Canadian postal codes  \
 0  NL NS PE NB QC ON MB SK AB BC NU/NT YT A B C E...
 1                                                 NS
 2                                                  B

                                           Unnamed: 2 Unnamed: 3 Unnamed: 4  \
 0  NL NS PE NB QC ON MB SK AB BC NU/NT YT A B C E...        NaN        NaN
 1                                                 PE         NB         QC
 2                                                  C          E          G

   Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10  \
 0        NaN        NaN        NaN        NaN        NaN         NaN
 1         QC         QC         ON         ON         ON          ON
 2          H          J          K          L          M           N

   Unnamed: 11 Unnamed: 12 Unnamed: 13 Unnamed: 14 Unnamed: 15 Unnamed: 16  \
 0         NaN         NaN         NaN         NaN         NaN         NaN
 1          ON          MB          SK          AB          BC       NU/NT
 2           P           R           S           T           V           X

   Unnamed: 17
 0         NaN
 1          YT
 2           Y  ,
   NL NS PE NB QC QC.1 QC.2 ON ON.1 ON.2 ON.3 ON.4 MB SK AB BC NU/NT YT
 0  A  B  C  E  G    H    J  K    L    M    N    P  R  S  T  V     X  Y]

In [99]:
# Our desired table is in the first list of df
df1 = pd.DataFrame(df[0])
df1

,Postal Code,Borough,Neighbourhood
0,M1A,Not assigned,Not assigned
1,M2A,Not assigned,Not assigned
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
...,...,...,...
175,M5Z,Not assigned,Not assigned
176,M6Z,Not assigned,Not assigned
177,M7Z,Not assigned,Not assigned
178,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."
179,M9Z,Not assigned,Not assigned

In [100]:
df1.shape

(180, 3)

In [101]:
df1.drop(df1[df1['Borough'] == 'Not assigned'].index, inplace = True) 
df1

,Postal Code,Borough,Neighbourhood
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
5,M6A,North York,"Lawrence Manor, Lawrence Heights"
6,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
...,...,...,...
160,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
165,M4Y,Downtown Toronto,Church and Wellesley
168,M7Y,East Toronto,"Business reply mail Processing Centre, South C..."
169,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu..."
178,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."

In [102]:
#Now we'll reset the inde
df1 = df1.reset_index(drop = True)
df1

,Postal Code,Borough,Neighbourhood
0,M3A,North York,Parkwoods
1,M4A,North York,Victoria Village
2,M5A,Downtown Toronto,"Regent Park, Harbourfront"
3,M6A,North York,"Lawrence Manor, Lawrence Heights"
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
...,...,...,...
98,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
99,M4Y,Downtown Toronto,Church and Wellesley
100,M7Y,East Toronto,"Business reply mail Processing Centre, South C..."
101,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu..."
102,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."

In [103]:
df1.shape

(103, 3)

In [107]:
df2 = pd.read_csv('http://cocl.us/Geospatial_data')

In [108]:
df2.shape

(103, 3)

In [104]:
df1.insert(3,'Latitude','')
df1.insert(4,'Longitude','')

In [105]:
df1 = df1.set_index('Postal Code')

In [109]:
df2 = df2.set_index('Postal Code')

In [88]:
index1 = list(df1.index)

In [110]:
for x in index1:
    df1.loc[x, 'Latitude'] = df2.loc[x, 'Latitude']
    df1.loc[x, 'Longitude'] = df2.loc[x, 'Longitude']

In [111]:
df1 = df1.reset_index()

In [112]:
df1

,Postal Code,Borough,Neighbourhood,Latitude,Longitude
0,M3A,North York,Parkwoods,43.7533,-79.3297
1,M4A,North York,Victoria Village,43.7259,-79.3156
2,M5A,Downtown Toronto,"Regent Park, Harbourfront",43.6543,-79.3606
3,M6A,North York,"Lawrence Manor, Lawrence Heights",43.7185,-79.4648
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government",43.6623,-79.3895
...,...,...,...,...,...
98,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North",43.6537,-79.5069
99,M4Y,Downtown Toronto,Church and Wellesley,43.6659,-79.3832
100,M7Y,East Toronto,"Business reply mail Processing Centre, South C...",43.6627,-79.3216
101,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu...",43.6363,-79.4985
102,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,...",43.6288,-79.521